from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

PROJECT_INFO = {
    "asset": "yourChar",
    "project_directory": r"Y:\LFDN\assets\characters",
    "sub_folders": ["maya", "data", "facial_rig_build"],
}

GROUPS_HIERARCHY = {
    "main": "face_grp",
    "geometry": "geometry_grp",
    "meshes": "meshes_grp",
    "rig_main": "rig_grp",
    "anim": "anim_grp",
    "joints": "joints_grp",
    "compil": "compil_grp",
    "bs": "bs_mesh_grp",
    "rig": "rig_mesh_grp",
    "tool": "tool_mesh_grp",
    "clusters": "clusters_grp",
    "rivet": "rivet_grp",
}

FACIAL_MODELING_HIERARCHY = {
    "body": {
        "name": "M_body_geo",
        "groups": [
            "geometry",
            "compil",
            "bs",
            "anim",
            "rig",
            "rig",
            "rig",
        ],
    },
    "eyebrows": {"name": "M_eyebrows_geo", "groups": ["geometry"]},
    "hair": {"name": "M_hair_geo", "groups": ["geometry", "compil"]},
    "eyelash": {
        "name": "M_eyelash_geo",
        "groups": ["geometry", "compil", "rig", "tool", "bs"],
    },
    "tongue": {"name": "M_tongue_geo", "groups": ["geometry", "compil"]},
    "upper_teeth": {
        "name": "M_upper_teeth_geo",
        "groups": ["geometry", "compil"],
    },
    "lower_teeth": {
        "name": "M_lower_teeth_geo",
        "groups": ["geometry", "compil"],
    },
    "eye": {"name": "{}_eye_grp", "groups": ["geometry", "compil"]},
}

BLENDSHAPE_CONNECTIONS = {
    "compil": ["geometry", "anim"],
    "rig": ["compil"],
    "bs": ["compil"],
    "tool": ["compil"],
}

DEFORMERS_STACK = {
    # Body deformers
    "M_body_geo": {
        "M_move_cluster": None,
        "{}_mouthCornerMicro_cluster": None,
        "{}_browCenter_cluster": None,
        "{}_browHair_cluster": None,
        "{}_browUnder_cluster": None,
        "M_glottisMain_cluster": None,
        "M_glottisGlobal_cluster": None,
    },
    "M_body_compil_mesh": {
        "M_body_skull_skinCluster": {
            "joints": ["M_base_04_jnt"],
            "use_hierarchy": True,
            "envelope": 1,
        },
        "lattice_lower_ffd1": None,
        "lattice_middle_ffd1": None,
        "lattice_upper_ffd1": None,
        "lattice_clusters_ffd1": None,
        "lattice_global_ffd1": None,
        "M_mouth_cluster": None,
        "{}_cheekboneOuter_cluster": None,
        "{}_cheekboneCenter_cluster": None,
        "{}_cheekboneInner_cluster": None,
        "{}_eye_region_cluster": None,
        "{}_eye_exept_eyeball_cluster": None,
        "{}_eye_global_cluster": None,
        "{}_cheekbone_follow_cluster": None,
        "M_noseFollow_cluster": None,
    },
    "M_body_rig01_mesh": {
        "M_body_rig01_skinCluster": {
            "joints": ["M_base_01_jnt"],
            "use_hierarchy": True,
            "envelope": 1,
        }
    },
    "M_body_rig02_mesh": {
        "M_body_rig02_skinCluster": {
            "joints": ["M_base_02_jnt"],
            "use_hierarchy": True,
            "envelope": 1,
        }
    },
    "M_body_rig03_mesh": {
        "M_body_rig03_skinCluster": {
            "joints": ["M_base_03_jnt"],
            "use_hierarchy": True,
            "envelope": 1,
        }
    },
    # Eyes deformers
    "{}_eye_grp": {"M_move_cluster": None},
    "{}_eye_compil_grp": {
        "{name}_skull_skinCluster": {
            "joints": ["M_skull_03_jnt"],
            "use_hierarchy": False,
            "envelope": 1,
        },
        "lattice_middle_ffd1": None,
        "lattice_upper_ffd1": None,
        "lattice_clusters_ffd1": None,
        "lattice_global_ffd1": None,
        "{side}_lattice_eyeCrop_ffd1": None,
        "{side}_eye_region_cluster": None,
        "{side}_eye_only_cluster": None,
    },
    # Hair deformers
    "M_hair_geo": {"M_move_cluster": None},
    "M_hair_compil_mesh": {
    "M_hair_skull_skinCluster": {
        "joints": ["M_base_04_jnt"],
        "use_hierarchy": True,
        "envelope": 1,
    },
    "lattice_lower_ffd1": None,
    "lattice_middle_ffd1": None,
    "lattice_upper_ffd1": None,
    "lattice_clusters_ffd1": None,
    "lattice_global_ffd1": None,
    },
    # Eyelash deformers
    "M_eyelash_geo": {
        "M_eyelash_geo_skull_off_skinCluster": {
            "joints": ["M_skull_03_jnt"],
            "use_hierarchy": False,
            "envelope": 0,
        },
        "M_move_cluster": None,
    },
    "M_eyelash_rig_mesh": {
        "{name}_skinCluster": {
            "joints": ["M_base_05_jnt"],
            "use_hierarchy": True,
            "envelope": 1,
        }
    },
    # Eyebrows deformers
    "M_eyebrows_geo": {
        "M_eyebrows_geo_skull_off_skinCluster": {
            "joints": ["M_skull_04_jnt"],
            "use_hierarchy": False,
            "envelope": 0,
        },
        "M_eyebrows_geo_wrap": {"source": "M_body_geo"},
    },
    # Tooth deformers
    "M_upper_teeth_geo": {"M_move_cluster": None},
    "M_upper_teeth_compil_mesh": {
        "M_upper_teeth_skull_skinCluster": {
            "joints": ["M_skull_01_jnt"],
            "use_hierarchy": False,
            "envelope": 1,
        },
        "lattice_lower_ffd1": None,
        "lattice_middle_ffd1": None,
        "lattice_upper_ffd1": None,
        "lattice_clusters_ffd1": None,
        "lattice_global_ffd1": None,
    },
    "M_lower_teeth_geo": {"M_move_cluster": None},
    "M_lower_teeth_compil_mesh": {
        "lattice_lower_ffd1": None,
        "lattice_middle_ffd1": None,
        "lattice_upper_ffd1": None,
        "lattice_clusters_ffd1": None,
        "lattice_global_ffd1": None,
    },
    # Tongue deformers
    "M_tongue_geo": {"M_move_cluster": None},
    "M_tongue_compil_mesh": {
        "lattice_lower_ffd1": None,
        "lattice_middle_ffd1": None,
        "lattice_upper_ffd1": None,
        "lattice_clusters_ffd1": None,
        "lattice_global_ffd1": None,
    },
}

DEFORMER_SUFFIX_ASSOCIATIONS = [
    {"suffix": "ffd1", "type": "ffd"},
    {"suffix": "cluster", "type": "cluster"},
    {"suffix": "blendShape", "type": "blendShape"},
    {"suffix": "wrap", "type": "wrap"},
    {"suffix": "proximityWrap", "type": "proximityWrap"},
    {"suffix": "shrinkWrap", "type": "shrinkWrap"},
    {"suffix": "wire", "type": "wire"},
    {"suffix": "skinCluster", "type": "skinCluster"},
]

TEMPLATE_SCENES_PATH = {
    "joint": r"N:\sandbox\svalran\providence\rebuild_providence\imported_scenes\providence_jnts.ma",
    "controller": r"N:\sandbox\svalran\providence\rebuild_providence\imported_scenes\providence_ctrl.ma",
    "cluster": r"N:\sandbox\svalran\providence\rebuild_providence\imported_scenes\providence_clusters.ma",
    "lattice": r"N:\sandbox\svalran\providence\rebuild_providence\imported_scenes\providence_lattices.ma",
}

ALL_CONNECTIONS = {
    "cluster": {
        "M_glottisGlobal_clusterHandle": {
            "M_glottis_global_ctrl.rotateX": "rotateX",
            "M_glottis_global_ctrl.rotateY": "rotateY",
            "M_glottis_global_ctrl.rotateZ": "rotateZ",
            "M_glottis_global_ctrl.scaleX": "scaleX",
            "M_glottis_global_ctrl.scaleY": "scaleY",
            "M_glottis_global_ctrl.scaleZ": "scaleZ",
            "M_glottis_global_ctrl.translateX": "translateX",
            "M_glottis_global_ctrl.translateY": "translateY",
            "M_glottis_global_ctrl.translateZ": "translateZ",
        },
        "M_glottisMain_clusterHandle": {
            "M_glottis_main_ctrl.rotateX": "rotateX",
            "M_glottis_main_ctrl.rotateY": "rotateY",
            "M_glottis_main_ctrl.rotateZ": "rotateZ",
            "M_glottis_main_ctrl.scaleX": "scaleX",
            "M_glottis_main_ctrl.scaleY": "scaleY",
            "M_glottis_main_ctrl.scaleZ": "scaleZ",
            "M_glottis_main_ctrl.translateX": "translateX",
            "M_glottis_main_ctrl.translateY": "translateY",
            "M_glottis_main_ctrl.translateZ": "translateZ",
        },
        "M_mouth_clusterHandle": {
            "M_mouth_cluster_translate_default_ratio_multiplyDivide.outputX": "translateX",
            "M_mouth_cluster_translate_default_ratio_multiplyDivide.outputY": "translateY",
            "M_mouth_cluster_translate_default_ratio_multiplyDivide.outputZ": "translateZ",
            "M_mouth_global_ctrl.rotateX": "rotateX",
            "M_mouth_global_ctrl.rotateY": "rotateY",
            "M_mouth_global_ctrl.rotateZ": "rotateZ",
            "M_mouth_global_ctrl.scaleX": "scaleX",
            "M_mouth_global_ctrl.scaleY": "scaleY",
            "M_mouth_global_ctrl.scaleZ": "scaleZ",
        },
        "M_noseFollow_clusterHandle": {
            "M_noseFollow_cluser_translate_plusMinusAverage.output3Dx": "translateX",
            "M_noseFollow_cluser_translate_plusMinusAverage.output3Dy": "translateY",
            "M_noseFollow_cluser_translate_plusMinusAverage.output3Dz": "translateZ",
            "M_noseFollow_cluster_rotate_plusMinusAverage.output3Dx": "rotateX",
            "M_noseFollow_cluster_rotate_plusMinusAverage.output3Dy": "rotateY",
            "M_noseFollow_cluster_rotate_plusMinusAverage.output3Dz": "rotateZ",
        },
        "{}_browCenter_clusterHandle": {
            "{}_browCenetr_cluster_translait_ratio_multiplyDivide.outputX": "translateX",
            "{}_browCenetr_cluster_translait_ratio_multiplyDivide.outputZ": "translateZ",
            "{}_brow_center_main_ctrl.rotateY": "rotateY",
            "{}_brow_center_main_ctrl.rotateZ": "rotateZ",
            "{}_brow_center_main_ctrl.scaleX": "scaleX",
            "{}_brow_center_main_ctrl.scaleY": "scaleY",
            "{}_brow_center_main_ctrl.scaleZ": "scaleZ",
        },
        "{}_browHair_clusterHandle": {
            "{}_browHair_ctrl.rotateX": "rotateX",
            "{}_browHair_ctrl.rotateY": "rotateY",
            "{}_browHair_ctrl.rotateZ": "rotateZ",
            "{}_browHair_ctrl.scaleX": "scaleX",
            "{}_browHair_ctrl.scaleY": "scaleY",
            "{}_browHair_ctrl.scaleZ": "scaleZ",
            "{}_browUnder_cluster_multiplyDivide.outputX": "translateX",
            "{}_browUnder_cluster_multiplyDivide.outputY": "translateY",
            "{}_browUnder_cluster_multiplyDivide.outputZ": "translateZ",
        },
        "{}_cheekboneCenter_clusterHandle": {
            "{}_cheekboneCenter_cluster_translate_multypliDivide.outputX": "translateX",
            "{}_cheekbone_center_main_ctrl.rotateX": "rotateX",
            "{}_cheekbone_center_main_ctrl.rotateY": "rotateY",
            "{}_cheekbone_center_main_ctrl.rotateZ": "rotateZ",
            "{}_cheekbone_center_main_ctrl.scaleX": "scaleX",
            "{}_cheekbone_center_main_ctrl.scaleY": "scaleY",
            "{}_cheekbone_center_main_ctrl.scaleZ": "scaleZ",
            "{}_cheekbone_center_main_ctrl.translateZ": "translateZ",
        },
        "{}_cheekboneInner_clusterHandle": {
            "{}_cheekboneInner_cluster_translate_multypliDivide.outputX": "translateX",
            "{}_cheekboneInner_cluster_translate_multypliDivide.outputZ": "translateZ",
            "{}_cheekbone_inner_main_ctrl.rotateX": "rotateX",
            "{}_cheekbone_inner_main_ctrl.rotateY": "rotateY",
            "{}_cheekbone_inner_main_ctrl.rotateZ": "rotateZ",
            "{}_cheekbone_inner_main_ctrl.scaleX": "scaleX",
            "{}_cheekbone_inner_main_ctrl.scaleY": "scaleY",
            "{}_cheekbone_inner_main_ctrl.scaleZ": "scaleZ",
        },
        "{}_cheekboneOuter_clusterHandle": {
            "{}_cheekboneOuter_cluster_translate_multypliDivide.outputX": "translateX",
            "{}_cheekboneOuter_cluster_translate_multypliDivide.outputZ": "translateZ",
            "{}_cheekbone_outer_main_ctrl.rotateX": "rotateX",
            "{}_cheekbone_outer_main_ctrl.rotateY": "rotateY",
            "{}_cheekbone_outer_main_ctrl.rotateZ": "rotateZ",
            "{}_cheekbone_outer_main_ctrl.scaleX": "scaleX",
            "{}_cheekbone_outer_main_ctrl.scaleY": "scaleY",
            "{}_cheekbone_outer_main_ctrl.scaleZ": "scaleZ",
        },
        "{}_cheekbone_follow_clusterHandle": {
            "{}_cheekbone_follow_plusMinusAverage.output3Dx": "translateX",
            "{}_cheekbone_follow_plusMinusAverage.output3Dy": "translateY",
        },
        "{}_eye_exept_eyeball_clusterHandle": {
            "{}_eye_cluster_global_2_ctrl.rotateX": "rotateX",
            "{}_eye_cluster_global_2_ctrl.rotateY": "rotateY",
            "{}_eye_cluster_global_2_ctrl.rotateZ": "rotateZ",
            "{}_eye_cluster_global_2_ctrl.scaleX": "scaleX",
            "{}_eye_cluster_global_2_ctrl.scaleY": "scaleY",
            "{}_eye_cluster_global_2_ctrl.scaleZ": "scaleZ",
            "{}_eye_cluster_global_2_ctrl.translateX": "translateX",
            "{}_eye_cluster_global_2_ctrl.translateY": "translateY",
            "{}_eye_cluster_global_2_ctrl.translateZ": "translateZ",
        },
        "{}_eye_global_clusterHandle": {
            "{}_eye_cluster_global_ctrl.scaleX": "scaleX",
            "{}_eye_cluster_global_ctrl.scaleY": "scaleY",
            "{}_eye_cluster_global_ctrl.scaleZ": "scaleZ",
            "{}_eye_cluster_global_ctrl.translateX": "translateX",
            "{}_eye_cluster_global_ctrl.translateY": "translateY",
            "{}_eye_cluster_global_ctrl.translateZ": "translateZ",
            "{}_eye_global_cluster_plusMinusAverage.output3Dx": "rotateX",
            "{}_eye_global_cluster_plusMinusAverage.output3Dy": "rotateY",
            "{}_eye_global_cluster_plusMinusAverage.output3Dz": "rotateZ",
        },
        "{}_eye_only_clusterHandle": {
            "{}_eye_cluster_global_ctrl.rotateX": "rotateX",
            "{}_eye_cluster_global_ctrl.rotateY": "rotateY",
            "{}_eye_cluster_global_ctrl.rotateZ": "rotateZ",
            "{}_eye_cluster_global_ctrl.scaleX": "scaleX",
            "{}_eye_cluster_global_ctrl.scaleY": "scaleY",
            "{}_eye_cluster_global_ctrl.scaleZ": "scaleZ",
            "{}_eye_cluster_global_ctrl.translateX": "translateX",
            "{}_eye_cluster_global_ctrl.translateY": "translateY",
            "{}_eye_cluster_global_ctrl.translateZ": "translateZ",
        },
        "{}_eye_region_clusterHandle": {
            "{}_eye_cluster_global_3_ctrl.rotateX": "rotateX",
            "{}_eye_cluster_global_3_ctrl.rotateY": "rotateY",
            "{}_eye_cluster_global_3_ctrl.rotateZ": "rotateZ",
            "{}_eye_cluster_global_3_ctrl.scaleX": "scaleX",
            "{}_eye_cluster_global_3_ctrl.scaleY": "scaleY",
            "{}_eye_cluster_global_3_ctrl.scaleZ": "scaleZ",
            "{}_eye_cluster_global_3_ctrl.translateX": "translateX",
            "{}_eye_cluster_global_3_ctrl.translateY": "translateY",
            "{}_eye_cluster_global_3_ctrl.translateZ": "translateZ",
        },
        "{}_mouthCornerMicro_clusterHandle": {
            "{}_mouth_corner_micro_ctrl.rotateX": "rotateX",
            "{}_mouth_corner_micro_ctrl.rotateY": "rotateY",
            "{}_mouth_corner_micro_ctrl.rotateZ": "rotateZ",
            "{}_mouth_corner_micro_ctrl.scaleX": "scaleX",
            "{}_mouth_corner_micro_ctrl.scaleY": "scaleY",
            "{}_mouth_corner_micro_ctrl.scaleZ": "scaleZ",
            "{}_mouth_corner_micro_translate_multiplyDivide.outputX": "translateX",
            "{}_mouth_corner_micro_translate_multiplyDivide.outputY": "translateY",
            "{}_mouth_corner_micro_translate_multiplyDivide.outputZ": "translateZ",
        },
        "{}_browUnder_clusterHandle": {
            "{}_browUnder_ctrl.translateX": "translateX",
            "{}_browUnder_ctrl.translateY": "translateY",
            "{}_browUnder_ctrl.translateZ": "translateZ",
            "{}_browUnder_ctrl.rotateX": "rotateX",
            "{}_browUnder_ctrl.rotateY": "rotateY",
            "{}_browUnder_ctrl.rotateZ": "rotateZ",
            "{}_browUnder_ctrl.scaleX": "scaleX",
            "{}_browUnder_ctrl.scaleY": "scaleY",
            "{}_browUnder_ctrl.scaleZ": "scaleZ",
        },
    },
    "joint": {
        "M_brow_global_jnt": {
            "M_brow_center_joint_ctrl.rotateX": "rotateX",
            "M_brow_center_joint_ctrl.rotateY": "rotateY",
            "M_brow_center_joint_ctrl.rotateZ": "rotateZ",
            "M_brow_center_joint_ctrl.scaleX": "scaleX",
            "M_brow_center_joint_ctrl.scaleY": "scaleY",
            "M_brow_center_joint_ctrl.scaleZ": "scaleZ",
            "M_brow_center_joint_ctrl.translateX": "translateX",
            "M_brow_center_joint_ctrl.translateY": "translateY",
            "M_brow_center_joint_ctrl.translateZ": "translateZ",
        },
        "M_jaw_main_jnt": {
            "M_jaw_joint_offset_ctrl.scaleX": "scaleX",
            "M_jaw_joint_offset_ctrl.scaleY": "scaleY",
            "M_jaw_joint_offset_ctrl.scaleZ": "scaleZ",
            "M_jaw_joint_offset_ctrl.translateX": "translateX",
            "M_jaw_joint_offset_ctrl.translateY": "translateY",
            "M_jaw_main_jnt_translateZ_plusMinusAverage.output3Dz": "translateZ",
            "M_jaw_main_rot_ratio_multiplyDivide.outputX": "rotateX",
            "M_jaw_main_rot_ratio_multiplyDivide.outputY": "rotateY",
            "M_jaw_main_rot_ratio_multiplyDivide.outputZ": "rotateZ",
        },
        "M_jaw_retain_jnt": {
            "M_jaw_retain_ctrl.scaleX": "scaleX",
            "M_jaw_retain_ctrl.scaleY": "scaleY",
            "M_jaw_retain_ctrl.scaleZ": "scaleZ",
            "M_jaw_retain_ctrl.translateX": "translateX",
            "M_jaw_retain_ctrl.translateY": "translateY",
            "M_jaw_retain_ctrl.translateZ": "translateZ",
            "M_jaw_retain_rot_ratio_multiplyDivide.outputX": "rotateX",
            "M_jaw_retain_rot_ratio_multiplyDivide.outputY": "rotateY",
            "M_jaw_retain_rot_ratio_multiplyDivide.outputZ": "rotateZ",
        },
        "M_lip_lower_global_jnt": {
            "M_lip_lower_global_ctrl.rotateY": "rotateY",
            "M_lip_lower_global_ctrl.rotateZ": "rotateZ",
            "M_lip_lower_global_ctrl.translateX": "translateX",
        },
        "M_lip_lower_main_jnt": {
            "M_lip_lower_main_ctrl.rotateY": "rotateY",
            "M_lip_lower_main_ctrl.rotateZ": "rotateZ",
            "M_lip_lower_main_ctrl.scaleX": "scaleX",
            "M_lip_lower_main_ctrl.scaleY": "scaleY",
            "M_lip_lower_main_ctrl.scaleZ": "scaleZ",
            "lips_lower_depth_plusMinusAverage.output3Dy": "translateZ",
        },
        "M_lip_upper_global_jnt": {
            "M_lip_upper_global_ctrl.rotateY": "rotateY",
            "M_lip_upper_global_ctrl.rotateZ": "rotateZ",
            "M_lip_upper_global_ctrl.translateX": "translateX",
        },
        "M_lip_upper_main_jnt": {
            "M_lip_upper_main_ctrl.rotateY": "rotateY",
            "M_lip_upper_main_ctrl.rotateZ": "rotateZ",
            "M_lip_upper_main_ctrl.scaleX": "scaleX",
            "M_lip_upper_main_ctrl.scaleY": "scaleY",
            "M_lip_upper_main_ctrl.scaleZ": "scaleZ",
            "lips_upper_depth_plusMinusAverage.output3Dy": "translateZ",
        },
        "M_mouth_main_jnt": {
            "M_mouth_main_ctrl.rotateX": "rotateX",
            "M_mouth_main_ctrl.rotateY": "rotateY",
            "M_mouth_main_ctrl.rotateZ": "rotateZ",
            "M_mouth_main_ctrl.translateZ": "translateZ",
        },
        "M_noseBridge_global_jnt": {
            "M_noseBridge_main_ctrl.rotateX": "rotateX",
            "M_noseBridge_main_ctrl.rotateY": "rotateY",
            "M_noseBridge_main_ctrl.rotateZ": "rotateZ",
            "M_noseBridge_main_ctrl.scaleX": "scaleX",
            "M_noseBridge_main_ctrl.scaleY": "scaleY",
            "M_noseBridge_main_ctrl.scaleZ": "scaleZ",
            "M_noseBridge_main_ctrl.translateX": "translateX",
            "M_noseBridge_main_ctrl.translateY": "translateY",
            "M_noseBridge_main_ctrl.translateZ": "translateZ",
        },
        "M_nose_base_jnt": {
            "M_noseBase_ctrl.rotateX": "rotateX",
            "M_noseBase_ctrl.rotateY": "rotateY",
            "M_noseBase_ctrl.rotateZ": "rotateZ",
            "M_noseBase_ctrl.scaleX": "scaleX",
            "M_noseBase_ctrl.scaleY": "scaleY",
            "M_noseBase_ctrl.scaleZ": "scaleZ",
            "M_noseBase_ctrl.translateX": "translateX",
            "M_noseBase_ctrl.translateY": "translateY",
            "M_noseBase_ctrl.translateZ": "translateZ",
        },
        "M_nose_global_jnt": {
            "M_nose_main_ctrl.rotateX": "rotateX",
            "M_nose_main_ctrl.rotateY": "rotateY",
            "M_nose_main_ctrl.rotateZ": "rotateZ",
            "M_nose_main_ctrl.scaleX": "scaleX",
            "M_nose_main_ctrl.scaleY": "scaleY",
            "M_nose_main_ctrl.scaleZ": "scaleZ",
            "M_nose_main_ctrl.translateX": "translateX",
            "M_nose_main_ctrl.translateY": "translateY",
            "M_nose_main_ctrl.translateZ": "translateZ",
        },
        "M_nose_root_jnt": {
            "M_nose_global_ctrl.rotateX": "rotateX",
            "M_nose_global_ctrl.rotateY": "rotateY",
            "M_nose_global_ctrl.rotateZ": "rotateZ",
            "M_nose_global_ctrl.scaleX": "scaleX",
            "M_nose_global_ctrl.scaleY": "scaleY",
            "M_nose_global_ctrl.scaleZ": "scaleZ",
            "M_nose_global_ctrl.translateX": "translateX",
            "M_nose_global_ctrl.translateY": "translateY",
            "M_nose_global_ctrl.translateZ": "translateZ",
        },
        "M_skull_01_jnt": {
            "M_skull01_ctrl.rotateX": "rotateX",
            "M_skull01_ctrl.rotateY": "rotateY",
            "M_skull01_ctrl.rotateZ": "rotateZ",
            "M_skull01_ctrl.scaleX": "scaleX",
            "M_skull01_ctrl.scaleY": "scaleY",
            "M_skull01_ctrl.scaleZ": "scaleZ",
            "M_skull01_ctrl.translateX": "translateX",
            "M_skull01_ctrl.translateY": "translateY",
            "M_skull01_ctrl.translateZ": "translateZ",
        },
        "M_skull_02_jnt": {
            "M_skull02_ctrl.rotateX": "rotateX",
            "M_skull02_ctrl.rotateY": "rotateY",
            "M_skull02_ctrl.rotateZ": "rotateZ",
            "M_skull02_ctrl.scaleX": "scaleX",
            "M_skull02_ctrl.scaleY": "scaleY",
            "M_skull02_ctrl.scaleZ": "scaleZ",
            "M_skull02_ctrl.translateX": "translateX",
            "M_skull02_ctrl.translateY": "translateY",
            "M_skull02_ctrl.translateZ": "translateZ",
        },
        "M_skull_03_jnt": {
            "M_skull03_ctrl.rotateX": "rotateX",
            "M_skull03_ctrl.rotateY": "rotateY",
            "M_skull03_ctrl.rotateZ": "rotateZ",
            "M_skull03_ctrl.scaleX": "scaleX",
            "M_skull03_ctrl.scaleY": "scaleY",
            "M_skull03_ctrl.scaleZ": "scaleZ",
            "M_skull03_ctrl.translateX": "translateX",
            "M_skull03_ctrl.translateY": "translateY",
            "M_skull03_ctrl.translateZ": "translateZ",
        },
        "M_skull_04_jnt": {
            "M_skull04_ctrl.rotateX": "rotateX",
            "M_skull04_ctrl.rotateY": "rotateY",
            "M_skull04_ctrl.rotateZ": "rotateZ",
            "M_skull04_ctrl.scaleX": "scaleX",
            "M_skull04_ctrl.scaleY": "scaleY",
            "M_skull04_ctrl.scaleZ": "scaleZ",
            "M_skull04_ctrl.translateX": "translateX",
            "M_skull04_ctrl.translateY": "translateY",
            "M_skull04_ctrl.translateZ": "translateZ",
        },
        "{}_brow_center_main_jnt": {
            "{}_brow_center_depthRatio_multDoubleLinear.output": "translateZ",
            "{}_brow_center_micro_ctrl.rotateX": "rotateX",
            "{}_brow_center_micro_ctrl.rotateY": "rotateY",
            "{}_brow_center_micro_ctrl.rotateZ": "rotateZ",
            "{}_brow_center_micro_ctrl.scaleX": "scaleX",
            "{}_brow_center_micro_ctrl.scaleY": "scaleY",
            "{}_brow_center_micro_ctrl.scaleZ": "scaleZ",
            "{}_brow_center_micro_ctrl.translateX": "translateX",
        },
        "{}_brow_inner_main_jnt": {
            "{}_brow_inner_depthRatio_multDoubleLinear.output": "translateZ",
            "{}_brow_inner_micro_ctrl.rotateX": "rotateX",
            "{}_brow_inner_micro_ctrl.rotateY": "rotateY",
            "{}_brow_inner_micro_ctrl.rotateZ": "rotateZ",
            "{}_brow_inner_micro_ctrl.scaleX": "scaleX",
            "{}_brow_inner_micro_ctrl.scaleY": "scaleY",
            "{}_brow_inner_micro_ctrl.scaleZ": "scaleZ",
            "{}_brow_inner_micro_ctrl.translateX": "translateX",
        },
        "{}_brow_jnt": {
            "{}_brow_joint_ctrl.rotateX": "rotateX",
            "{}_brow_joint_ctrl.rotateY": "rotateY",
            "{}_brow_joint_ctrl.rotateZ": "rotateZ",
            "{}_brow_joint_ctrl.scaleX": "scaleX",
            "{}_brow_joint_ctrl.scaleY": "scaleY",
            "{}_brow_joint_ctrl.scaleZ": "scaleZ",
            "{}_brow_joint_ctrl.translateX": "translateX",
            "{}_brow_joint_ctrl.translateY": "translateY",
            "{}_brow_joint_ctrl.translateZ": "translateZ",
        },
        "{}_brow_outer_main_jnt": {
            "{}_brow_outer_depthRatio_multDoubleLinear.output": "translateZ",
            "{}_brow_outer_micro_ctrl.rotateX": "rotateX",
            "{}_brow_outer_micro_ctrl.rotateY": "rotateY",
            "{}_brow_outer_micro_ctrl.rotateZ": "rotateZ",
            "{}_brow_outer_micro_ctrl.scaleX": "scaleX",
            "{}_brow_outer_micro_ctrl.scaleY": "scaleY",
            "{}_brow_outer_micro_ctrl.scaleZ": "scaleZ",
            "{}_brow_outer_micro_ctrl.translateX": "translateX",
        },
        "{}_cheek_main_jnt": {
            "{}_cheek_main_ctrl.jntDepth": "translateZ",
            "{}_cheek_main_ctrl.jntSide": "translateX",
            "{}_cheek_main_ctrl.jntUpDn": "translateY",
            "{}_cheek_main_ctrl.rotateX": "rotateX",
            "{}_cheek_main_ctrl.rotateY": "rotateY",
            "{}_cheek_main_ctrl.rotateZ": "rotateZ",
            "{}_cheek_main_ctrl.scaleX": "scaleX",
            "{}_cheek_main_ctrl.scaleY": "scaleY",
            "{}_cheek_main_ctrl.scaleZ": "scaleZ",
        },
        "{}_ear_bot_main_jnt": {
            "{}_ear_bot_ctrl.rotateX": "rotateX",
            "{}_ear_bot_ctrl.rotateY": "rotateY",
            "{}_ear_bot_ctrl.rotateZ": "rotateZ",
            "{}_ear_bot_ctrl.scaleX": "scaleX",
            "{}_ear_bot_ctrl.scaleY": "scaleY",
            "{}_ear_bot_ctrl.scaleZ": "scaleZ",
            "{}_ear_bot_ctrl.translateX": "translateX",
            "{}_ear_bot_ctrl.translateY": "translateY",
            "{}_ear_bot_ctrl.translateZ": "translateZ",
        },
        "{}_ear_global_jnt": {
            "{}_ear_global_ctrl.rotateX": "rotateX",
            "{}_ear_global_ctrl.rotateY": "rotateY",
            "{}_ear_global_ctrl.rotateZ": "rotateZ",
            "{}_ear_global_ctrl.scaleX": "scaleX",
            "{}_ear_global_ctrl.scaleY": "scaleY",
            "{}_ear_global_ctrl.scaleZ": "scaleZ",
            "{}_ear_global_ctrl.translateX": "translateX",
            "{}_ear_global_ctrl.translateY": "translateY",
            "{}_ear_global_ctrl.translateZ": "translateZ",
        },
        "{}_ear_main_jnt": {
            "{}_ear_main_ctrl.rotateX": "rotateX",
            "{}_ear_main_ctrl.rotateY": "rotateY",
            "{}_ear_main_ctrl.rotateZ": "rotateZ",
            "{}_ear_main_ctrl.scaleX": "scaleX",
            "{}_ear_main_ctrl.scaleY": "scaleY",
            "{}_ear_main_ctrl.scaleZ": "scaleZ",
            "{}_ear_main_ctrl.translateX": "translateX",
            "{}_ear_main_ctrl.translateY": "translateY",
            "{}_ear_main_ctrl.translateZ": "translateZ",
        },
        "{}_ear_top_main_jnt": {
            "{}_ear_top_ctrl.rotateX": "rotateX",
            "{}_ear_top_ctrl.rotateY": "rotateY",
            "{}_ear_top_ctrl.rotateZ": "rotateZ",
            "{}_ear_top_ctrl.scaleX": "scaleX",
            "{}_ear_top_ctrl.scaleY": "scaleY",
            "{}_ear_top_ctrl.scaleZ": "scaleZ",
            "{}_ear_top_ctrl.translateX": "translateX",
            "{}_ear_top_ctrl.translateY": "translateY",
            "{}_ear_top_ctrl.translateZ": "translateZ",
        },
        "{}_eye_loCrease_inner_jnt": {
            "{}_eyelid_lowerInner_crease_ctrl.rotateX": "rotateX",
            "{}_eyelid_lowerInner_crease_ctrl.rotateY": "rotateY",
            "{}_eyelid_lowerInner_crease_ctrl.rotateZ": "rotateZ",
            "{}_eyelid_lowerInner_crease_ctrl.scaleX": "scaleX",
            "{}_eyelid_lowerInner_crease_ctrl.scaleY": "scaleY",
            "{}_eyelid_lowerInner_crease_ctrl.scaleZ": "scaleZ",
            "{}_eyelid_lowerInner_crease_ctrl.translateX": "translateX",
            "{}_eyelid_lowerInner_crease_ctrl.translateY": "translateY",
            "{}_eyelid_lowerInner_crease_ctrl.translateZ": "translateZ",
        },
        "{}_eye_loCrease_mid_jnt": {
            "{}_eyelid_lowerCenter_crease_ctrl.rotateX": "rotateX",
            "{}_eyelid_lowerCenter_crease_ctrl.rotateY": "rotateY",
            "{}_eyelid_lowerCenter_crease_ctrl.rotateZ": "rotateZ",
            "{}_eyelid_lowerCenter_crease_ctrl.scaleX": "scaleX",
            "{}_eyelid_lowerCenter_crease_ctrl.scaleY": "scaleY",
            "{}_eyelid_lowerCenter_crease_ctrl.scaleZ": "scaleZ",
            "{}_eyelid_lowerCenter_crease_ctrl.translateX": "translateX",
            "{}_eyelid_lowerCenter_crease_ctrl.translateY": "translateY",
            "{}_eyelid_lowerCenter_crease_ctrl.translateZ": "translateZ",
        },
        "{}_eye_loCrease_outer_jnt": {
            "{}_eyelid_lowerOuter_crease_ctrl.rotateX": "rotateX",
            "{}_eyelid_lowerOuter_crease_ctrl.rotateY": "rotateY",
            "{}_eyelid_lowerOuter_crease_ctrl.rotateZ": "rotateZ",
            "{}_eyelid_lowerOuter_crease_ctrl.scaleX": "scaleX",
            "{}_eyelid_lowerOuter_crease_ctrl.scaleY": "scaleY",
            "{}_eyelid_lowerOuter_crease_ctrl.scaleZ": "scaleZ",
            "{}_eyelid_lowerOuter_crease_ctrl.translateX": "translateX",
            "{}_eyelid_lowerOuter_crease_ctrl.translateY": "translateY",
            "{}_eyelid_lowerOuter_crease_ctrl.translateZ": "translateZ",
        },
        "{}_eye_upCrease_inner_jnt": {
            "{}_eyelid_upperInner_crease_ctrl.rotateX": "rotateX",
            "{}_eyelid_upperInner_crease_ctrl.rotateY": "rotateY",
            "{}_eyelid_upperInner_crease_ctrl.rotateZ": "rotateZ",
            "{}_eyelid_upperInner_crease_ctrl.scaleX": "scaleX",
            "{}_eyelid_upperInner_crease_ctrl.scaleY": "scaleY",
            "{}_eyelid_upperInner_crease_ctrl.scaleZ": "scaleZ",
            "{}_eyelid_upperInner_crease_ctrl.translateX": "translateX",
            "{}_eyelid_upperInner_crease_ctrl.translateY": "translateY",
            "{}_eyelid_upperInner_crease_ctrl.translateZ": "translateZ",
        },
        "{}_eye_upCrease_mid_jnt": {
            "{}_eyelid_upperCenter_crease_ctrl.rotateX": "rotateX",
            "{}_eyelid_upperCenter_crease_ctrl.rotateY": "rotateY",
            "{}_eyelid_upperCenter_crease_ctrl.rotateZ": "rotateZ",
            "{}_eyelid_upperCenter_crease_ctrl.scaleX": "scaleX",
            "{}_eyelid_upperCenter_crease_ctrl.scaleY": "scaleY",
            "{}_eyelid_upperCenter_crease_ctrl.scaleZ": "scaleZ",
            "{}_eyelid_upperCenter_crease_ctrl.translateX": "translateX",
            "{}_eyelid_upperCenter_crease_ctrl.translateY": "translateY",
            "{}_eyelid_upperCenter_crease_ctrl.translateZ": "translateZ",
        },
        "{}_eye_upCrease_outer_jnt": {
            "{}_eyelid_upperOuter_crease_ctrl.rotateX": "rotateX",
            "{}_eyelid_upperOuter_crease_ctrl.rotateY": "rotateY",
            "{}_eyelid_upperOuter_crease_ctrl.rotateZ": "rotateZ",
            "{}_eyelid_upperOuter_crease_ctrl.scaleX": "scaleX",
            "{}_eyelid_upperOuter_crease_ctrl.scaleY": "scaleY",
            "{}_eyelid_upperOuter_crease_ctrl.scaleZ": "scaleZ",
            "{}_eyelid_upperOuter_crease_ctrl.translateX": "translateX",
            "{}_eyelid_upperOuter_crease_ctrl.translateY": "translateY",
            "{}_eyelid_upperOuter_crease_ctrl.translateZ": "translateZ",
        },
        "{}_eyelid_inner_corner_main_jnt": {
            "{}_eyelid_inner_corner_ctrl.rotateX": "rotateX",
            "{}_eyelid_inner_corner_ctrl.rotateY": "rotateY",
            "{}_eyelid_inner_corner_ctrl.rotateZ": "rotateZ",
            "{}_eyelid_inner_corner_ctrl.scaleX": "scaleX",
            "{}_eyelid_inner_corner_ctrl.scaleY": "scaleY",
            "{}_eyelid_inner_corner_ctrl.scaleZ": "scaleZ",
            "{}_eyelid_inner_corner_ctrl.translateX": "translateX",
            "{}_eyelid_inner_corner_ctrl.translateY": "translateY",
            "{}_eyelid_inner_corner_ctrl.translateZ": "translateZ",
        },
        "{}_eyelid_inner_corner_micro_main_jnt": {
            "{}_eyelid_inner_corner_micro_ctrl.rotateX": "rotateX",
            "{}_eyelid_inner_corner_micro_ctrl.rotateY": "rotateY",
            "{}_eyelid_inner_corner_micro_ctrl.rotateZ": "rotateZ",
            "{}_eyelid_inner_corner_micro_ctrl.scaleX": "scaleX",
            "{}_eyelid_inner_corner_micro_ctrl.scaleY": "scaleY",
            "{}_eyelid_inner_corner_micro_ctrl.scaleZ": "scaleZ",
            "{}_eyelid_inner_corner_micro_ctrl.translateX": "translateX",
            "{}_eyelid_inner_corner_micro_ctrl.translateY": "translateY",
            "{}_eyelid_inner_corner_micro_ctrl.translateZ": "translateZ",
        },
        "{}_eyelid_outer_corner_main_jnt": {
            "{}_eyelid_outer_corner_ctrl.rotateX": "rotateX",
            "{}_eyelid_outer_corner_ctrl.rotateY": "rotateY",
            "{}_eyelid_outer_corner_ctrl.rotateZ": "rotateZ",
            "{}_eyelid_outer_corner_ctrl.scaleX": "scaleX",
            "{}_eyelid_outer_corner_ctrl.scaleY": "scaleY",
            "{}_eyelid_outer_corner_ctrl.scaleZ": "scaleZ",
            "{}_eyelid_outer_corner_ctrl.translateX": "translateX",
            "{}_eyelid_outer_corner_ctrl.translateY": "translateY",
            "{}_eyelid_outer_corner_ctrl.translateZ": "translateZ",
        },
        "{}_eyelid_outer_corner_micro_main_jnt": {
            "{}_eyelid_outer_corner_micro_ctrl.rotateX": "rotateX",
            "{}_eyelid_outer_corner_micro_ctrl.rotateY": "rotateY",
            "{}_eyelid_outer_corner_micro_ctrl.rotateZ": "rotateZ",
            "{}_eyelid_outer_corner_micro_ctrl.scaleX": "scaleX",
            "{}_eyelid_outer_corner_micro_ctrl.scaleY": "scaleY",
            "{}_eyelid_outer_corner_micro_ctrl.scaleZ": "scaleZ",
            "{}_eyelid_outer_corner_micro_ctrl.translateX": "translateX",
            "{}_eyelid_outer_corner_micro_ctrl.translateY": "translateY",
            "{}_eyelid_outer_corner_micro_ctrl.translateZ": "translateZ",
        },
        "{}_inner_lower_eyelid_jnt": {
            "{}_eyelid_lower_inner_micro_ctrl.rotateY": "rotateY",
            "{}_eyelid_lower_inner_micro_ctrl.rotateZ": "rotateZ",
            "{}_eyelid_lower_inner_micro_ctrl.scaleX": "scaleX",
            "{}_eyelid_lower_inner_micro_ctrl.scaleY": "scaleY",
            "{}_eyelid_lower_inner_micro_ctrl.scaleZ": "scaleZ",
            "{}_eyelid_lower_inner_micro_ctrl.translateX": "translateX",
            "{}_eyelid_lower_inner_micro_ctrl.translateZ": "translateZ",
            "{}_eyelid_lower_multiplyDivide.outputX": "rotateX",
        },
        "{}_inner_upper_eyelash_jnt": {
            "{}_eyelash_rotX_plusMinusAverage.output3Dx": "rotateX",
            "{}_eyelash_rotY_plusMinusAverage.output3Dx": "rotateY",
            "{}_eyelash_rotZ_plusMinusAverage.output3Dx": "rotateZ",
            "{}_eyelash_upper_inner_ctrl.translateX": "translateX",
            "{}_eyelash_upper_inner_ctrl.translateY": "translateY",
            "{}_eyelash_upper_inner_ctrl.translateZ": "translateZ",
        },
        "{}_inner_upper_eyelid_jnt": {
            "{}_eyelid_upper_inner_micro_ctrl.rotateY": "rotateY",
            "{}_eyelid_upper_inner_micro_ctrl.rotateZ": "rotateZ",
            "{}_eyelid_upper_inner_micro_ctrl.scaleX": "scaleX",
            "{}_eyelid_upper_inner_micro_ctrl.scaleY": "scaleY",
            "{}_eyelid_upper_inner_micro_ctrl.scaleZ": "scaleZ",
            "{}_eyelid_upper_inner_micro_ctrl.translateX": "translateX",
            "{}_eyelid_upper_inner_micro_ctrl.translateZ": "translateZ",
            "{}_eyelid_upper_multiplyDivide.outputX": "rotateX",
        },
        "{}_lip_lower_main_jnt": {
            "{}_lip_lower_main_ctrl.rotateX": "rotateX",
            "{}_lip_lower_main_ctrl.rotateY": "rotateY",
            "{}_lip_lower_main_ctrl.rotateZ": "rotateZ",
            "{}_lip_lower_main_ctrl.scaleX": "scaleX",
            "{}_lip_lower_main_ctrl.scaleY": "scaleY",
            "{}_lip_lower_main_ctrl.scaleZ": "scaleZ",
            "{}_lip_lower_main_ctrl.translateX": "translateX",
        },
        "L_lip_lower_main_jnt": {
            "lips_lower_depth_plusMinusAverage.output3Dx": "translateZ",
        },
        "R_lip_lower_main_jnt": {
            "lips_lower_depth_plusMinusAverage.output3Dz": "translateZ",
        },
        "{}_lip_upper_main_jnt": {
            "{}_lip_upper_main_ctrl.rotateX": "rotateX",
            "{}_lip_upper_main_ctrl.rotateY": "rotateY",
            "{}_lip_upper_main_ctrl.rotateZ": "rotateZ",
            "{}_lip_upper_main_ctrl.scaleX": "scaleX",
            "{}_lip_upper_main_ctrl.scaleY": "scaleY",
            "{}_lip_upper_main_ctrl.scaleZ": "scaleZ",
            "{}_lip_upper_main_ctrl.translateX": "translateX",
        },
        "L_lip_upper_main_jnt": {
            "lips_upper_depth_plusMinusAverage.output3Dx": "translateZ",
        },
        "R_lip_upper_main_jnt": {
            "lips_upper_depth_plusMinusAverage.output3Dz": "translateZ",
        },
        "{}_lower_eyelid_jnt": {
            "{}_eyelid_lower_main_ctrl.scaleX": "scaleX",
            "{}_eyelid_lower_main_ctrl.scaleY": "scaleY",
            "{}_eyelid_lower_main_ctrl.scaleZ": "scaleZ",
            "{}_eyelid_lower_main_ctrl.translateZ": "translateZ",
            "{}_eyelid_lower_main_rotY_multiplyDivide.outputX": "rotateY",
        },
        "{}_mid_lower_eyelid_jnt": {
            "{}_eyelid_lower_center_micro_ctrl.rotateY": "rotateY",
            "{}_eyelid_lower_center_micro_ctrl.rotateZ": "rotateZ",
            "{}_eyelid_lower_center_micro_ctrl.scaleX": "scaleX",
            "{}_eyelid_lower_center_micro_ctrl.scaleY": "scaleY",
            "{}_eyelid_lower_center_micro_ctrl.scaleZ": "scaleZ",
            "{}_eyelid_lower_center_micro_ctrl.translateX": "translateX",
            "{}_eyelid_lower_center_micro_ctrl.translateZ": "translateZ",
            "{}_eyelid_lower_multiplyDivide.outputY": "rotateX",
        },
        "{}_mid_upper_eyelash_jnt": {
            "{}_eyelash_rotX_plusMinusAverage.output3Dy": "rotateX",
            "{}_eyelash_rotY_plusMinusAverage.output3Dy": "rotateY",
            "{}_eyelash_rotZ_plusMinusAverage.output3Dy": "rotateZ",
            "{}_eyelash_upper_center_ctrl.translateX": "translateX",
            "{}_eyelash_upper_center_ctrl.translateY": "translateY",
            "{}_eyelash_upper_center_ctrl.translateZ": "translateZ",
        },
        "{}_mid_upper_eyelid_jnt": {
            "{}_eyelid_upper_center_micro_ctrl.rotateY": "rotateY",
            "{}_eyelid_upper_center_micro_ctrl.rotateZ": "rotateZ",
            "{}_eyelid_upper_center_micro_ctrl.scaleX": "scaleX",
            "{}_eyelid_upper_center_micro_ctrl.scaleY": "scaleY",
            "{}_eyelid_upper_center_micro_ctrl.scaleZ": "scaleZ",
            "{}_eyelid_upper_center_micro_ctrl.translateX": "translateX",
            "{}_eyelid_upper_center_micro_ctrl.translateZ": "translateZ",
            "{}_eyelid_upper_multiplyDivide.outputY": "rotateX",
        },
        "{}_mouth_corner_main_jnt": {
            "{}_mouth_corner_ctrl.rotateX": "rotateX",
            "{}_mouth_corner_ctrl.rotateY": "rotateY",
            "{}_mouth_corner_ctrl.rotateZ": "rotateZ",
            "{}_mouth_corner_ctrl.scaleX": "scaleX",
            "{}_mouth_corner_ctrl.scaleY": "scaleY",
            "{}_mouth_corner_ctrl.scaleZ": "scaleZ",
            "{}_mouth_corner_depthRatio_multDoubleLinear.output": "translateZ",
        },
        "{}_noseBridge_main_jnt": {
            "{}_noseBridge_main_ctrl.rotateX": "rotateX",
            "{}_noseBridge_main_ctrl.rotateY": "rotateY",
            "{}_noseBridge_main_ctrl.rotateZ": "rotateZ",
            "{}_noseBridge_main_ctrl.scaleX": "scaleX",
            "{}_noseBridge_main_ctrl.scaleY": "scaleY",
            "{}_noseBridge_main_ctrl.scaleZ": "scaleZ",
            "{}_noseBridge_main_ctrl.translateX": "translateX",
            "{}_noseBridge_main_ctrl.translateY": "translateY",
            "{}_noseBridge_main_ctrl.translateZ": "translateZ",
        },
        "{}_nostril_main_jnt": {
            "{}_nostril_main_ctrl.rotateX": "rotateX",
            "{}_nostril_main_ctrl.rotateY": "rotateY",
            "{}_nostril_main_ctrl.rotateZ": "rotateZ",
            "{}_nostril_main_ctrl.scaleX": "scaleX",
            "{}_nostril_main_ctrl.scaleY": "scaleY",
            "{}_nostril_main_ctrl.scaleZ": "scaleZ",
            "{}_nostril_main_jnt_plusMinusAverage.output3Dx": "translateX",
            "{}_nostril_main_jnt_plusMinusAverage.output3Dy": "translateY",
            "{}_nostril_main_jnt_plusMinusAverage.output3Dz": "translateZ",
        },
        "{}_outer_lower_eyelid_jnt": {
            "{}_eyelid_lower_multiplyDivide.outputZ": "rotateX",
            "{}_eyelid_lower_outer_micro_ctrl.rotateY": "rotateY",
            "{}_eyelid_lower_outer_micro_ctrl.rotateZ": "rotateZ",
            "{}_eyelid_lower_outer_micro_ctrl.scaleX": "scaleX",
            "{}_eyelid_lower_outer_micro_ctrl.scaleY": "scaleY",
            "{}_eyelid_lower_outer_micro_ctrl.scaleZ": "scaleZ",
            "{}_eyelid_lower_outer_micro_ctrl.translateX": "translateX",
            "{}_eyelid_lower_outer_micro_ctrl.translateZ": "translateZ",
        },
        "{}_outer_upper_eyelash_jnt": {
            "{}_eyelash_rotX_plusMinusAverage.output3Dz": "rotateX",
            "{}_eyelash_rotY_plusMinusAverage.output3Dz": "rotateY",
            "{}_eyelash_rotZ_plusMinusAverage.output3Dz": "rotateZ",
            "{}_eyelash_upper_outer_ctrl.translateX": "translateX",
            "{}_eyelash_upper_outer_ctrl.translateY": "translateY",
            "{}_eyelash_upper_outer_ctrl.translateZ": "translateZ",
        },
        "{}_outer_upper_eyelid_jnt": {
            "{}_eyelid_upper_multiplyDivide.outputZ": "rotateX",
            "{}_eyelid_upper_outer_micro_ctrl.rotateY": "rotateY",
            "{}_eyelid_upper_outer_micro_ctrl.rotateZ": "rotateZ",
            "{}_eyelid_upper_outer_micro_ctrl.scaleX": "scaleX",
            "{}_eyelid_upper_outer_micro_ctrl.scaleY": "scaleY",
            "{}_eyelid_upper_outer_micro_ctrl.scaleZ": "scaleZ",
            "{}_eyelid_upper_outer_micro_ctrl.translateX": "translateX",
            "{}_eyelid_upper_outer_micro_ctrl.translateZ": "translateZ",
        },
        "{}_upper_eyelash_jnt": {
            "{}_eyelash_upper_main_ctrl.translateX": "translateX",
            "{}_eyelash_upper_main_ctrl.translateY": "translateY",
            "{}_eyelash_upper_main_ctrl.translateZ": "translateZ",
        },
        "{}_upper_eyelid_jnt": {
            "{}_eyelid_upper_main_ctrl.scaleX": "scaleX",
            "{}_eyelid_upper_main_ctrl.scaleY": "scaleY",
            "{}_eyelid_upper_main_ctrl.scaleZ": "scaleZ",
            "{}_eyelid_upper_main_ctrl.translateZ": "translateZ",
            "{}_eyelid_upper_main_rotY_multiplyDivide.outputX": "rotateY",
        },
    },
    "lattice": {
        "M_lower_lattice_clusterHandleHandle": {
            "M_lower_lattice_clusterHandle_ctrl.rotateX": "rotateX",
            "M_lower_lattice_clusterHandle_ctrl.rotateY": "rotateY",
            "M_lower_lattice_clusterHandle_ctrl.rotateZ": "rotateZ",
            "M_lower_lattice_clusterHandle_ctrl.scaleX": "scaleX",
            "M_lower_lattice_clusterHandle_ctrl.scaleY": "scaleY",
            "M_lower_lattice_clusterHandle_ctrl.scaleZ": "scaleZ",
            "M_lower_lattice_clusterHandle_ctrl.translateX": "translateX",
            "M_lower_lattice_clusterHandle_ctrl.translateY": "translateY",
            "M_lower_lattice_clusterHandle_ctrl.translateZ": "translateZ",
        },
        "M_mid_lattice_wire_clst": {
            "M_lattice_mid_rotate_multiplyDivide.outputX": "rotateX",
            "M_lattice_mid_rotate_multiplyDivide.outputY": "rotateY",
            "M_lattice_mid_rotate_multiplyDivide.outputZ": "rotateZ",
            "M_lattice_mid_scale_multiplyDivide.outputX": "scaleX",
            "M_lattice_mid_scale_multiplyDivide.outputY": "scaleY",
            "M_lattice_mid_scale_multiplyDivide.outputZ": "scaleZ",
            "M_lattice_mid_translate_multiplyDivide.outputX": "translateX",
            "M_lattice_mid_translate_multiplyDivide.outputY": "translateY",
            "M_lattice_mid_translate_multiplyDivide.outputZ": "translateZ",
        },
        "M_middle_lattice_clusterHandleHandle": {
            "M_middle_lattice_clusterHandle_ctrl.rotateX": "rotateX",
            "M_middle_lattice_clusterHandle_ctrl.rotateY": "rotateY",
            "M_middle_lattice_clusterHandle_ctrl.rotateZ": "rotateZ",
            "M_middle_lattice_clusterHandle_ctrl.scaleX": "scaleX",
            "M_middle_lattice_clusterHandle_ctrl.scaleY": "scaleY",
            "M_middle_lattice_clusterHandle_ctrl.scaleZ": "scaleZ",
            "M_middle_lattice_clusterHandle_ctrl.translateX": "translateX",
            "M_middle_lattice_clusterHandle_ctrl.translateY": "translateY",
            "M_middle_lattice_clusterHandle_ctrl.translateZ": "translateZ",
        },
        "M_upper_lattice_clusterHandleHandle": {
            "M_upper_lattice_clusterHandle_ctrl.rotateX": "rotateX",
            "M_upper_lattice_clusterHandle_ctrl.rotateY": "rotateY",
            "M_upper_lattice_clusterHandle_ctrl.rotateZ": "rotateZ",
            "M_upper_lattice_clusterHandle_ctrl.scaleX": "scaleX",
            "M_upper_lattice_clusterHandle_ctrl.scaleY": "scaleY",
            "M_upper_lattice_clusterHandle_ctrl.scaleZ": "scaleZ",
            "M_upper_lattice_clusterHandle_ctrl.translateX": "translateX",
            "M_upper_lattice_clusterHandle_ctrl.translateY": "translateY",
            "M_upper_lattice_clusterHandle_ctrl.translateZ": "translateZ",
        },
        "lattice_global_bendX_handleShape": {
            "lattice_global_bend_multiplyDivide.outputX": "curvature"
        },
        "lattice_global_bendZ_handleShape": {
            "lattice_global_bend_multiplyDivide.outputZ": "curvature"
        },
        "lattice_global_squash_handleShape": {
            "lattice_global_squash_ratio_multiplyDivide.outputX": "factor"
        },
        "lattice_global_twist_handleShape": {
            "lattice_global_rotateY_multiplyDivide.outputX": "endAngle"
        },
        "lattice_lower_bendX_handleShape": {
            "M_lattice_lower_multiplyDivide.outputX": "curvature"
        },
        "lattice_lower_bendZ_handleShape": {
            "M_lattice_lower_multiplyDivide.outputZ": "curvature"
        },
        "lattice_lower_ffd_blendShape": {
            "M_lattice_lower_condition.outColorR": "lattice_lower_squash_ffd",
            "M_lattice_lower_stretchSquash_multiplyDivide.outputX": "lattice_lower_stretch_ffd",
        },
        "lattice_lower_twist_handleShape": {
            "M_lattice_lower_multiplyDivide.outputY": "endAngle"
        },
        "lattice_upper_bendX_handleShape": {
            "M_lattice_upper_multiplyDivide.outputX": "curvature"
        },
        "lattice_upper_bendZ_handleShape": {
            "M_lattice_upper_multiplyDivide.outputZ": "curvature"
        },
        "lattice_upper_ffd_blendShape": {
            "M_lattice_upper_condition.outColorR": "lattice_upper_stretch_ffd",
            "M_lattice_upper_ctretchSquash_multiplyDivide.outputX": "lattice_upper_squash_ffd",
        },
        "lattice_upper_twist_handleShape": {
            "M_lattice_upper_multiplyDivide.outputY": "endAngle"
        },
        "{}_lower_lattice_clusterHandleHandle": {
            "{}_lower_lattice_clusterHandle_ctrl.rotateX": "rotateX",
            "{}_lower_lattice_clusterHandle_ctrl.rotateY": "rotateY",
            "{}_lower_lattice_clusterHandle_ctrl.rotateZ": "rotateZ",
            "{}_lower_lattice_clusterHandle_ctrl.scaleX": "scaleX",
            "{}_lower_lattice_clusterHandle_ctrl.scaleY": "scaleY",
            "{}_lower_lattice_clusterHandle_ctrl.scaleZ": "scaleZ",
            "{}_lower_lattice_clusterHandle_ctrl.translateX": "translateX",
            "{}_lower_lattice_clusterHandle_ctrl.translateY": "translateY",
            "{}_lower_lattice_clusterHandle_ctrl.translateZ": "translateZ",
        },
        "{}_middle_lattice_clusterHandleHandle": {
            "{}_middle_lattice_clusterHandle_ctrl.rotateX": "rotateX",
            "{}_middle_lattice_clusterHandle_ctrl.rotateY": "rotateY",
            "{}_middle_lattice_clusterHandle_ctrl.rotateZ": "rotateZ",
            "{}_middle_lattice_clusterHandle_ctrl.scaleX": "scaleX",
            "{}_middle_lattice_clusterHandle_ctrl.scaleY": "scaleY",
            "{}_middle_lattice_clusterHandle_ctrl.scaleZ": "scaleZ",
            "{}_middle_lattice_clusterHandle_ctrl.translateX": "translateX",
            "{}_middle_lattice_clusterHandle_ctrl.translateY": "translateY",
            "{}_middle_lattice_clusterHandle_ctrl.translateZ": "translateZ",
        },
        "{}_upper_lattice_clusterHandleHandle": {
            "{}_upper_lattice_clusterHandle_ctrl.rotateX": "rotateX",
            "{}_upper_lattice_clusterHandle_ctrl.rotateY": "rotateY",
            "{}_upper_lattice_clusterHandle_ctrl.rotateZ": "rotateZ",
            "{}_upper_lattice_clusterHandle_ctrl.scaleX": "scaleX",
            "{}_upper_lattice_clusterHandle_ctrl.scaleY": "scaleY",
            "{}_upper_lattice_clusterHandle_ctrl.scaleZ": "scaleZ",
            "{}_upper_lattice_clusterHandle_ctrl.translateX": "translateX",
            "{}_upper_lattice_clusterHandle_ctrl.translateY": "translateY",
            "{}_upper_lattice_clusterHandle_ctrl.translateZ": "translateZ",
        },
    },
    "controller": {
        "M_body_bs_bcs": {
            "M_jawOpen_multDoubleLinear.output": "jawOpen",
            "M_jaw_main_ctrl.translateX": "jawSide",
            "M_lip_lower_main_ctrl.curl": "lowerLipsCurlZipL",
            "M_lip_lower_main_ctrl.puff": "lowerLipsPuffZipL",
            "M_lip_lower_main_lip_zip_plusMinAverage.output3Dx": "presetFalloff[6].pFalloff[0].pFalloff_Position",
            "M_lip_lower_main_lip_zip_plusMinAverage.output3Dy": "presetFalloff[6].pFalloff[1].pFalloff_Position",
            "M_lip_lower_main_lip_zip_plusMinAverage.output3Dz": "presetFalloff[6].pFalloff[2].pFalloff_Position",
            "M_lip_lower_main_plusMinusAverage.output3Dx": "lowerLipsUpdnZipL",
            "M_lip_upper_main_ctrl.curl": "upperLipsCurlZipL",
            "M_lip_upper_main_ctrl.puff": "upperLipsPuffZipL",
            "M_lip_upper_main_lip_zip_plusMinAverage.output3Dx": "presetFalloff[5].pFalloff[0].pFalloff_Position",
            "M_lip_upper_main_lip_zip_plusMinAverage.output3Dy": "presetFalloff[5].pFalloff[1].pFalloff_Position",
            "M_lip_upper_main_lip_zip_plusMinAverage.output3Dz": "presetFalloff[5].pFalloff[2].pFalloff_Position",
            "M_lip_upper_main_plusMinusAverage.output3Dx": "upperLipsUpDnZipL",
            "M_mouth_main_ctrl.retain": "jawRetain",
            "M_mouth_main_ctrl.translateX": "mouthSide",
            "M_mouth_main_ctrl.translateY": "mouthUpdn",
            "l_brow_wrinkle_plusMinusAvege.output2Dx": "browWrinkleL",
            "l_brow_wrinkle_plusMinusAvege.output2Dy": "browWrinkleR",
            "lips_lower_rot_plusMinusAverage.output3Dx": "lowerLipsCurlL",
            "lips_lower_rot_plusMinusAverage.output3Dz": "lowerLipsCurlR",
            "lips_lower_upDn_plusMinusAverage.output3Dx": "lowerLipsUpdnL",
            "lips_lower_upDn_plusMinusAverage.output3Dz": "lowerLipsUpdnR",
            "lips_lowerer_puff_plusMinusAverage.output3Dx": "lowerLipsPuffL",
            "lips_lowerer_puff_plusMinusAverage.output3Dz": "lowerLipsPuffR",
            "lips_upper_puff_plusMinusAverage.output3Dx": "upperLipsPuffL",
            "lips_upper_puff_plusMinusAverage.output3Dz": "upperLipsPuffR",
            "lips_upper_rot_plusMinusAverage.output3Dx": "upperLipsCurlL",
            "lips_upper_rot_plusMinusAverage.output3Dz": "upperLipsCurlR",
            "lips_upper_upDn_plusMinusAverage.output3Dx": "upperLipsUpDnL",
            "lips_upper_upDn_plusMinusAverage.output3Dz": "upperLipsUpDnR",
            "{}_brow_center_main_ctrl.translateY": "browCenterUpDn{}",
            "{}_brow_center_main_ctrl_rotX_multiplyDivide.outputX": "XXbrowsCenterRoll{}",
            "{}_brow_center_micro_ctrl.translateY": "browCenterMicroUpDn{}",
            "{}_brow_inner_curl_ctrl.translateY": "browsInnerMicroCurl{}",
            "{}_brow_inner_micro_ctrl.translateY": "browInnerMicroUpDn{}",
            "{}_brow_inner_sharp_ctrl.translateY": "browSharpUpDn{}",
            "{}_brow_outer_curl_ctrl.translateY": "browsOuterMicroCurl{}",
            "{}_brow_outer_micro_ctrl.translateY": "browOuterMicroUpDn{}",
            "{}_brows_UpDn_plusMinusAverage.output3Dx": "browInnerUpDn{}",
            "{}_brows_UpDn_plusMinusAverage.output3Dz": "browOuterUpDn{}",
            "{}_brows_outIn_plusMinusAverage.output3Dx": "browInnerOutIn{}",
            "{}_brows_outIn_plusMinusAverage.output3Dz": "browOuterOutIn{}",
            "{}_brows_rotX_plusMinusAverage.output3Dx": "XXbrowsInnerRoll{}",
            "{}_brows_rotX_plusMinusAverage.output3Dz": "XXbrowsOuterRoll{}",
            "{}_cheek_main_ctrl.translateX": "cheekPuffOUtIn{}",
            "{}_cheek_main_ctrl.translateY": "cheekPuffUpDn{}",
            "{}_cheek_main_ctrl.translateZ": "cheekPuff{}",
            "{}_cheekbone_UpDn_plusMinusAverage.output3Dx": "cheekboneInnerUpDn{}",
            "{}_cheekbone_UpDn_plusMinusAverage.output3Dz": "cheekboneOuterUpDn{}",
            "{}_cheekbone_center_main_ctrl.lowLidFollow": "cheekboneLidFollow{}",
            "{}_cheekbone_center_main_plusMinusAverage.output3Dx": "cheekboneCenterUpDn{}",
            "{}_eyelid_lower_blink_multiplyDivide.outputX": "eyelidLowerInnerUpDn{}",
            "{}_eyelid_lower_blink_multiplyDivide.outputY": "eyelidLowerCenterUpDn{}",
            "{}_eyelid_lower_blink_multiplyDivide.outputZ": "eyelidLowerOuterUpDn{}",
            "{}_eyelid_upper_blink_multiplyDivide.outputX": "eyelidUpperInnerUpDn{}",
            "{}_eyelid_upper_blink_multiplyDivide.outputY": "eyelidUpperCenterUpDn{}",
            "{}_eyelid_upper_blink_multiplyDivide.outputZ": "eyelidUpperOuterUpDn{}",
            "{}_lip_lower_sharp_ctrl.translateY": "lowerLipsSharpUpdn{}",
            "{}_lip_upper_sharp_ctrl.translateY": "upperLipsSharpUpdn{}",
            "{}_mouth_corner_ctrl.translateX": "cornerOutIn{}",
            "{}_mouth_corner_ctrl.translateY": "cornerUpdn{}",
            "L_mouth_corner_retain_zip_plusMinAverage.output3Dx": "presetFalloff[9].pFalloff[0].pFalloff_Position",
            "L_mouth_corner_retain_zip_plusMinAverage.output3Dy": "presetFalloff[9].pFalloff[2].pFalloff_Position",
            "R_mouth_corner_retain_zip_plusMinAverage.output3Dx": "presetFalloff[10].pFalloff[0].pFalloff_Position",
            "R_mouth_corner_retain_zip_plusMinAverage.output3Dy": "presetFalloff[10].pFalloff[2].pFalloff_Position",
            "{}_nostril_main_ctrl.dilate": "noseDilate{}",
            "{}_nostril_main_ctrl.snarl": "snarl{}",
            "{}_nostril_main_ctrl.translateY": "sneer{}",
        },
        "M_eyelash_bs_bcs": {
            "{}_eyelash_upper_bypass_multiplyDivide.outputX": "eyelashUpperInnerUpDn{}",
            "{}_eyelash_upper_bypass_multiplyDivide.outputY": "eyelashUpperCenterUpDn{}",
            "{}_eyelash_upper_bypass_multiplyDivide.outputZ": "eyelashUpperOuterUpDn{}",
            "{}_eyelid_upper_blink_multiplyDivide.outputX": "eyelidUpperInnerUpDn{}",
            "{}_eyelid_upper_blink_multiplyDivide.outputY": "eyelidUpperCenterUpDn{}",
            "{}_eyelid_upper_blink_multiplyDivide.outputZ": "eyelidUpperOuterUpDn{}",
        },
    },
    "bcs": {
        "M_body_bs_bcs_transfer": "M_body_bs_mesh",
        "M_eyelash_bs_bcs_transfer": "M_eyelash_bs_mesh",
    },
}

SKIP_CONTROLLERS = [
    "L_browsTwk_main_0_ctrl",
    "L_browsTwk_main_1_ctrl",
    "L_browsTwk_micro_0_ctrl",
    "L_browsTwk_micro_1_ctrl",
    "L_browsTwk_micro_2_ctrl",
    "L_browsTwk_micro_3_ctrl",
    "L_browsTwk_micro_4_ctrl",
    "L_browsTwk_micro_5_ctrl",
    "L_browsTwk_tangente_0_0_ctrl",
    "L_browsTwk_tangente_0_1_ctrl",
    "L_browsTwk_tangente_1_0_ctrl",
    "L_browsTwk_tangente_1_1_ctrl",
    "L_eye_ctrl",
    "L_eye_lookat_ctrl",
    "L_eye_specular_ctrl",
    "L_lowerLipTwk_main_0_ctrl",
    "L_lowerLipTwk_main_1_ctrl",
    "L_lowerLipTwk_micro_0_ctrl",
    "L_lowerLipTwk_micro_1_ctrl",
    "L_lowerLipTwk_micro_2_ctrl",
    "L_lowerLipTwk_micro_3_ctrl",
    "L_lowerLipTwk_micro_4_ctrl",
    "L_lowerLipTwk_micro_5_ctrl",
    "L_lowerLipTwk_tangente_0_0_ctrl",
    "L_lowerLipTwk_tangente_0_1_ctrl",
    "L_lowerLipTwk_tangente_1_0_ctrl",
    "L_lowerLipTwk_tangente_1_1_ctrl",
    "L_lowerTeeth_micro_01_ctrl",
    "L_lowerTeeth_micro_02_ctrl",
    "L_upperLipTwk_main_0_ctrl",
    "L_upperLipTwk_main_1_ctrl",
    "L_upperLipTwk_micro_0_ctrl",
    "L_upperLipTwk_micro_1_ctrl",
    "L_upperLipTwk_micro_2_ctrl",
    "L_upperLipTwk_micro_3_ctrl",
    "L_upperLipTwk_micro_4_ctrl",
    "L_upperLipTwk_micro_5_ctrl",
    "L_upperLipTwk_tangente_0_0_ctrl",
    "L_upperLipTwk_tangente_0_1_ctrl",
    "L_upperLipTwk_tangente_1_0_ctrl",
    "L_upperLipTwk_tangente_1_1_ctrl",
    "L_upperTeeth_micro_01_ctrl",
    "L_upperTeeth_micro_02_ctrl",
    "M_browsTwk_main_0_ctrl",
    "M_browsTwk_tangente_0_0_ctrl",
    "M_browsTwk_tangente_0_1_ctrl",
    "M_eye_lookat_ctrl",
    "M_eye_lookat_offset_ctrl",
    "M_lowerLipTwk_main_0_ctrl",
    "M_lowerLipTwk_tangente_0_0_ctrl",
    "M_lowerLipTwk_tangente_0_1_ctrl",
    "M_lowerTeeth_main_ctrl",
    "M_lowerTeeth_micro_01_ctrl",
    "M_tongue_fk_01_ctrl",
    "M_tongue_fk_02_ctrl",
    "M_tongue_fk_03_ctrl",
    "M_tongue_fk_04_ctrl",
    "M_tongue_ik_01_ctrl",
    "M_tongue_ik_03_ctrl",
    "M_tongue_ik_04_ctrl",
    "M_tongue_ik_05_ctrl",
    "M_tongue_ik_07_ctrl",
    "M_upperLipTwk_main_0_ctrl",
    "M_upperLipTwk_tangente_0_0_ctrl",
    "M_upperLipTwk_tangente_0_1_ctrl",
    "M_upperTeeth_main_ctrl",
    "M_upperTeeth_micro_01_ctrl",
    "R_browsTwk_main_0_ctrl",
    "R_browsTwk_main_1_ctrl",
    "R_browsTwk_micro_6_ctrl",
    "R_browsTwk_micro_7_ctrl",
    "R_browsTwk_micro_8_ctrl",
    "R_browsTwk_micro_9_ctrl",
    "R_browsTwk_micro_10_ctrl",
    "R_browsTwk_micro_11_ctrl",
    "R_browsTwk_tangente_0_0_ctrl",
    "R_browsTwk_tangente_0_1_ctrl",
    "R_browsTwk_tangente_1_0_ctrl",
    "R_browsTwk_tangente_1_1_ctrl",
    "R_eye_ctrl",
    "R_eye_lookat_ctrl",
    "R_eye_specular_ctrl",
    "R_lowerLipTwk_main_0_ctrl",
    "R_lowerLipTwk_main_1_ctrl",
    "R_lowerLipTwk_micro_6_ctrl",
    "R_lowerLipTwk_micro_7_ctrl",
    "R_lowerLipTwk_micro_8_ctrl",
    "R_lowerLipTwk_micro_9_ctrl",
    "R_lowerLipTwk_micro_10_ctrl",
    "R_lowerLipTwk_micro_11_ctrl",
    "R_lowerLipTwk_tangente_0_0_ctrl",
    "R_lowerLipTwk_tangente_0_1_ctrl",
    "R_lowerLipTwk_tangente_1_0_ctrl",
    "R_lowerLipTwk_tangente_1_1_ctrl",
    "R_lowerTeeth_micro_01_ctrl",
    "R_lowerTeeth_micro_02_ctrl",
    "R_upperLipTwk_main_0_ctrl",
    "R_upperLipTwk_main_1_ctrl",
    "R_upperLipTwk_micro_6_ctrl",
    "R_upperLipTwk_micro_7_ctrl",
    "R_upperLipTwk_micro_8_ctrl",
    "R_upperLipTwk_micro_9_ctrl",
    "R_upperLipTwk_micro_10_ctrl",
    "R_upperLipTwk_micro_11_ctrl",
    "R_upperLipTwk_tangente_0_0_ctrl",
    "R_upperLipTwk_tangente_0_1_ctrl",
    "R_upperLipTwk_tangente_1_0_ctrl",
    "R_upperLipTwk_tangente_1_1_ctrl",
    "R_upperTeeth_micro_01_ctrl",
    "R_upperTeeth_micro_02_ctrl",
]
